@startuml

'title T4_cross_region_entry_exit

state A {
    state B {
        state C
    }
}
state End <<end>>

state A : entry/ self.action("Entered State A")
state A : exit/ self.action("Exited State A")
state B : entry/ self.action("Entered State B")
state B : exit/ self.action("Exited State B")
state C : entry/ self.action("Entered State C")
state C : exit/ self.action("Exited State C")

[*] --> C : /self.action("Transition 1")
C --> End : /self.action("Transition 2")

@enduml

@startexpected
Transition 1
Entered State A
Entered State B
Entered State C
Exited State C
Exited State B
Exited State A
Transition 2
@endexpected